#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
RESET='\033[0m'

display_banner() {
    clear
    local delay=0.08

    local lines=(
            "                    "
            "      \\     /      "
            "       \\   /       "
            "        \\ /        "
             "         V         "
             "        vex        "
    )

    local colors=("$RED" "$YELLOW" "$GREEN" "$CYAN" "$MAGENTA" "$RED")
    for ((i=0; i<${#lines[@]}; i++)); do
        echo -e "${colors[i]}${lines[$i]}${RESET}"
        sleep $delay
    done

    sleep 0.3
    echo -e "${MAGENTA}========================================${RESET}"
    echo -e "${MAGENTA}   ${CYAN}Welcome to your ${YELLOW}Vim${CYAN} Environment   ${MAGENTA}${RESET}"
    echo -e "${MAGENTA}========================================${RESET}"
    echo

}
