#!/bin/bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${BASE_DIR}/../src"
PLUGGED_DIR="$CONFIG_DIR/plugins"
PLUG_VIM="$HOME/.vim/autoload/plug.vim"

source "${BASE_DIR}/colors"
source "${BASE_DIR}/logger"
source "${BASE_DIR}/display"
display_banner

if ! command -v vim &> /dev/null; then
    log_step "Vim not found. Installing..."
    sudo pacman -S vim
else
    log_warning "Vim is already installed."
fi

log_success "Setting up symbolic link for .vimrc..."
if [ -L "$HOME/.vimrc" ]; then
    log_warning "Existing .vimrc symlink found. Removing..."
    rm "$HOME/.vimrc"
fi
ln -s "$CONFIG_DIR/.vimrc" "$HOME/.vimrc"

if [ ! -f "$PLUG_VIM" ]; then
    log_step "Installing vim-plug..."
    curl -fLo "$PLUG_VIM" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
    log_step "vim-plug is already installed."
fi

log_step "Setting executable permissions for setup.sh..."
chmod +x "$0"

log_step "Installing plugins..."
vim +PlugInstall +qall

echo
echo -e "${CYAN}Your new Vim configuration is ready to use.${RESET}"
echo